### ISSUE TITLE
Error when trying to install

### ISSUE THREAD

**Issue by kisa360** [UserUnknownFactor/GIMP3-ML#11]
I get the following error when trying to install the plugin.
Failed to activate the created environment.
At line:10 char:5
+     throw "Failed to activate the created environment."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to activ...ed environment.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to activate the created environment.

**Desktop (please complete the following information):**
 - OS Version: [e.g. Windows 11]
 - GIMP Version: [e.g. 2.99.16]

**Comment by Lokdal** [comment]
More details on this problem.
1. I have the same issue as OP when installing Python 3.12 from the Windows Store.
2. If I install Python 3.12 from the website for my user only, then the gimpenv folder is created wherever the install.cmd is located. The plug-in is not added to the folder \AppData\Roaming\GIMP\2.99\plug-ins.
3. If I install Python 3.12 from the website for all users, then the gimpenv folder is created in Windows/system32. The plug-in is not added to the folder C:\Program Files\GIMP 2.99\plug-ins (which does not exist).

Windows 11
GIMP 2.99.16
Python 3.12.2

**Comment by 0reo** [comment]
same problem here

```
-----------Installing GIMP-ML-----------
Requirement already satisfied: virtualenv in c:\users\oreo\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (20.21.0)
Requirement already satisfied: distlib<1,>=0.3.6 in c:\users\oreo\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from virtualenv) (0.3.6)
Requirement already satisfied: platformdirs<4,>=2.4 in c:\users\oreo\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from virtualenv) (3.2.0)
Requirement already satisfied: filelock<4,>=3.4.1 in c:\users\oreo\appdata\local\packages\pythonsoftwarefoundation.python.3.10_qbz5n2kfra8p0\localcache\local-packages\python310\site-packages (from virtualenv) (3.10.7)

created virtual environment CPython3.10.11.final.0-64 in 7507ms
  creator Venv(dest=E:\dev-personal\GIMP3-ML\gimpenv3, clear=False, no_vcs_ignore=False, global=False, describe=CPython3Windows)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=C:\Users\Oreo\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypa\virtualenv)
    added seed packages: pip==23.0.1, setuptools==67.6.1, wheel==0.40.0
  activators BashActivator,BatchActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
Failed to activate the created environment.
At line:10 char:5
+     throw "Failed to activate the created environment."
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to activ...ed environment.:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to activate the created environment.

```

windows 10
gimp 2.99.12
python 3.10.11

**Comment by 0reo** [comment]
manually calling
`.\gimpenv3\Scripts\activate`
after line 4 of install.cmd seems to fix the problem.  Looks like it assumes running `python -m virtualenv gimpenv3` will activate the virtual environment, and then checks if the current python path is from that environment before moving forward.  But on my end, the environment is only being created once I manually call the activate script.  install.cmd should be modified so that it will
- check if we're actually using the environment
- if not, check if the environment directory is created
- if it was created, run activation script
- check if the environment is active again

**Comment by UserUnknownFactor** [comment]
Something like this maybe:
```cmd
python -m pip install virtualenv
if not exist "gimpenv3" (
    echo Creating virtual environment gimpenv3...
    python -m venv gimpenv3
    if errorlevel 1 (
        echo Error creating the virtual environment. Please check your Python installation.
        exit /b 1
    )
)
echo Activating virtual gimpenv3...
call .\gimpenv3\Scripts\activate
if errorlevel 1 (
    echo Error activating the virtual environment. Please make sure it's correctly set up.
    exit /b 1
)
```
