### ISSUE TITLE
install.cmd fails if 2 versions of gimp are installed

### ISSUE THREAD

**Issue by 0reo** [UserUnknownFactor/GIMP3-ML#12]
**Describe the bug**
As the title states, if you try to run the install script with more than 1 version of gimp installed, it will fail.  Seems to be because of line 26/27 in install.cmd
https://github.com/UserUnknownFactor/GIMP3-ML/blob/df66bb11f44ac5c39d7bea63774b8fa7611204a9/install.cmd#L26-L27
$gimpdir will have 2 paths, and so $gimp won't work

**To Reproduce**
1. Have 2 versions of Gimp installed(Say, a stable 2.10 build, and 2.99.16)
2. run install script
3. See error
 ```
dir : Cannot find path 'C:\Program Files\GIMP 2 C:\Program Files\GIMP 2.99\bin' because it does not exist.
At line:26 char:10
+ $gimp = (dir  "$($gimpdir)\bin\gimp-console-*.exe").FullName
+          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Program File...s\GIMP 2.99\bin:String) [Get-ChildItem], ItemNotFoundException
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.GetChildItemCommand

Could not find GIMP! You will have to add '$($PSScriptRoot)\plugins' to Preferences -> Folders -> Plug-ins manually.
At line:28 char:5
+     throw "Could not find GIMP! You will have to add '$pluginsDir' to ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find ...g-ins manually.:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find GIMP! You will have to add '$($PSScriptRoot)\plugins' to Preferences -> Folders -> Plug-ins manually.
```

**Desktop (please complete the following information):**
 - OS Version: Windows 10
 - GIMP Version: 2.99.10 and any other version

**Comment by UserUnknownFactor** [comment]
Feel free to create a pull request for the fix if you have an idea how to fix it.
