### ISSUE TITLE
Plug-ins must be installed in subdirectories.

### ISSUE THREAD

**Issue by xXPerditorXx** [UserUnknownFactor/GIMP3-ML#6]
**Describe the bug**
Set the folder to gimp-plugins but in console, it prints `Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/color_palette.png': plug-ins must be installed in subdirectories.
`

**To Reproduce**
git clone https://github.com/UserUnknownFactor/GIMP3-ML.git and add the 'plugins' folder to gimp plugins

**Screenshots**
![image](https://github.com/UserUnknownFactor/GIMP3-ML/assets/60017046/0de25def-7b36-4ddd-8e6e-8d82b571d6aa)

**Console Error**
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/color_palette.png': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/colorpalette.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/deblur.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/deepcolor.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/deepdehaze.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/deepdenoise.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/deepmatting.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/enlighten.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/facegen.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/faceparse.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/inpainting.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/installGimpML.sh': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/interpolateframes.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/invert.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/kmeans.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/monodepth.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/semseg.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/super_resolution.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/syncWeights.py': plug-ins must be installed in subdirectories.
Skipping potential plug-in '/mnt/daten/GIMP-ML/gimp-plugins/update.py': plug-ins must be installed in subdirectories.

**Desktop**
-     OS Version: Arch Linux 6.3.6 KDE Plasma 5.27.5
-     GIMP Version: 2.99.14

**Comment by UserUnknownFactor** [comment]
What project are you even talking about? They **are** in subdirectories already, check the source tree.
